# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_detection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='face_detection.proto',
  package='FaceDetection',
  syntax='proto3',
  serialized_options=b'\n%com.bytedance.videoarch.facedetectionB\tFaceProtoP\001\242\002\003RTG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x66\x61\x63\x65_detection.proto\x12\rFaceDetection\"L\n\x0b\x44\x65tectedObj\x12\n\n\x02lx\x18\x02 \x01(\x05\x12\n\n\x02ly\x18\x03 \x01(\x05\x12\n\n\x02rx\x18\x04 \x01(\x05\x12\n\n\x02ry\x18\x05 \x01(\x05\x12\r\n\x05score\x18\x07 \x01(\x02\"E\n\x0e\x46\x61\x63\x65\x44\x65tRequest\x12\x11\n\timageData\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\nconfThresh\x18\x03 \x01(\x02\">\n\x0f\x46\x61\x63\x65\x44\x65tResponse\x12+\n\x07\x64\x65tObjs\x18\x01 \x03(\x0b\x32\x1a.FaceDetection.DetectedObj2\\\n\x0e\x46\x61\x63\x65\x44\x65tService\x12J\n\x07predict\x12\x1d.FaceDetection.FaceDetRequest\x1a\x1e.FaceDetection.FaceDetResponse\"\x00\x42:\n%com.bytedance.videoarch.facedetectionB\tFaceProtoP\x01\xa2\x02\x03RTGb\x06proto3'
)




_DETECTEDOBJ = _descriptor.Descriptor(
  name='DetectedObj',
  full_name='FaceDetection.DetectedObj',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lx', full_name='FaceDetection.DetectedObj.lx', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ly', full_name='FaceDetection.DetectedObj.ly', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rx', full_name='FaceDetection.DetectedObj.rx', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ry', full_name='FaceDetection.DetectedObj.ry', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='FaceDetection.DetectedObj.score', index=4,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=115,
)


_FACEDETREQUEST = _descriptor.Descriptor(
  name='FaceDetRequest',
  full_name='FaceDetection.FaceDetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageData', full_name='FaceDetection.FaceDetRequest.imageData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='FaceDetection.FaceDetRequest.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confThresh', full_name='FaceDetection.FaceDetRequest.confThresh', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=186,
)


_FACEDETRESPONSE = _descriptor.Descriptor(
  name='FaceDetResponse',
  full_name='FaceDetection.FaceDetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='detObjs', full_name='FaceDetection.FaceDetResponse.detObjs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=250,
)

_FACEDETRESPONSE.fields_by_name['detObjs'].message_type = _DETECTEDOBJ
DESCRIPTOR.message_types_by_name['DetectedObj'] = _DETECTEDOBJ
DESCRIPTOR.message_types_by_name['FaceDetRequest'] = _FACEDETREQUEST
DESCRIPTOR.message_types_by_name['FaceDetResponse'] = _FACEDETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectedObj = _reflection.GeneratedProtocolMessageType('DetectedObj', (_message.Message,), {
  'DESCRIPTOR' : _DETECTEDOBJ,
  '__module__' : 'face_detection_pb2'
  # @@protoc_insertion_point(class_scope:FaceDetection.DetectedObj)
  })
_sym_db.RegisterMessage(DetectedObj)

FaceDetRequest = _reflection.GeneratedProtocolMessageType('FaceDetRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACEDETREQUEST,
  '__module__' : 'face_detection_pb2'
  # @@protoc_insertion_point(class_scope:FaceDetection.FaceDetRequest)
  })
_sym_db.RegisterMessage(FaceDetRequest)

FaceDetResponse = _reflection.GeneratedProtocolMessageType('FaceDetResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACEDETRESPONSE,
  '__module__' : 'face_detection_pb2'
  # @@protoc_insertion_point(class_scope:FaceDetection.FaceDetResponse)
  })
_sym_db.RegisterMessage(FaceDetResponse)


DESCRIPTOR._options = None

_FACEDETSERVICE = _descriptor.ServiceDescriptor(
  name='FaceDetService',
  full_name='FaceDetection.FaceDetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=252,
  serialized_end=344,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='FaceDetection.FaceDetService.predict',
    index=0,
    containing_service=None,
    input_type=_FACEDETREQUEST,
    output_type=_FACEDETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEDETSERVICE)

DESCRIPTOR.services_by_name['FaceDetService'] = _FACEDETSERVICE

# @@protoc_insertion_point(module_scope)
